### ISSUE TITLE
Princeton WordNet lexicon id

### ISSUE THREAD

**Issue by goodmami** [bond-lab/omw-data#1]
The `id` attribute of the lexicons for the Princeton WordNet's versions 3.0 and 3.1 are `pwn30` and `pwn31`, respectively. Is it possible to just have `pwn` and rely on the `version` attribute to differentiate, or do we need to keep these IDs for some reason?

**Comment by fcbond** [comment]
I think it is ok to change the id to just `pwn`.

**Comment by goodmami** [comment]
Ok. Turns out this is used throughout, like for the ids of lexical entries, synsets, etc. I'll change all to `pwn`.
