### ISSUE TITLE
Is the WordNet name trademarked by Princeton?

### ISSUE THREAD

**Issue by ekaf** [bond-lab/omw-data#14]
According to @ChristianeFellbaum (https://github.com/bond-lab/omw-data/issues/5#issuecomment-925058271):

> the name "WordNet" is trademarked by Princeton and cannot and should not be used by other, similar databases.

Ths seems to imply that some wordnet projects that use an uppercase "N", like f. ex. plWordNet need to use lowercase "n" as in "Wordnet" instead.

_Updated_: However, according to the USPT0 (https://github.com/bond-lab/omw-data/issues/14#issuecomment-947338649), this trademark was cancelled in 2016. Does it mean that anybody is now free to use the name "WordNet" as they wish?

**Comment by ekaf** [comment]
This may actually be a non-issue, since the Princeton trademark was cancelled back in 2016, according to the following record from the United States Patent and Trademark Office (https://tmsearch.uspto.gov/):

>   Word Mark WORDNET
>   Goods and Services (CANCELLED) IC 009. US 038. G & S: computer programs
   in the nature of an inter-relational dictionary/lexicon of the English
   language for use in information retrieval, machine translation,
   vocabulary instruction and text editing. FIRST USE: 19920600. FIRST USE
   IN COMMERCE: 19920600
   Mark Drawing Code (1) TYPED DRAWING
   Serial Number 74207961
   Filing Date September 30, 1991
   Current Basis 1A
   Original Filing Basis 1B
   Published for Opposition July 14, 1992
   Registration Number 1784773
   Registration Date July 27, 1993
   Owner (REGISTRANT) Trustees of Princeton University, The CORPORATION
   NEW JERSEY Princeton University, New South Building, 4th Floor P.O. Box
   36 PRINCETON NEW JERSEY 085440036
   Attorney of Record RICHARD C. WOODBRIDGE
   Type of Mark TRADEMARK
   Register PRINCIPAL
   Affidavit Text SECT 15. SECT 8 (6-YR). SECTION 8(10-YR) 20030221.
   Renewal 1ST RENEWAL 20030221
   Live/Dead Indicator DEAD
   Cancellation Date February 5, 2016

**Comment by ChristianeFellbaum** [comment]
Aha!

Christiane

________________________________

**Comment by fcbond** [comment]
We have renamed the wordnet in the latest release.
