### ISSUE TITLE
SyntacticBehaviour, Examples and Frames

### ISSUE THREAD

**Issue by FredsoNerd** [bond-lab/omw-data#4]
In discussion with @arademaker, we encountered what look like mislead about the definition of `SyntacticBehaviour` and `Examples` when defining `LexicalEntry`s in https://github.com/goodmami/wn/blob/main/wn/index.toml#L23-L25.

It looks like the occurrences of data defined as `SyntacticBehaviour` in that file should be defined as `Example`, while `SyntacticBehaviour` should contain the info about `Frames` from PWN.

Example:
```xml
<LexicalEntry id="pwn30-overbear-v" >
      [...]

      <SyntacticBehaviour subcategorizationFrame="The banks %s the check"/>
      <SyntacticBehaviour subcategorizationFrame="They %s the car down the avenue"/>
      <SyntacticBehaviour subcategorizationFrame="The coins %s "/>
      <SyntacticBehaviour subcategorizationFrame="They %s the coin "/>
    </LexicalEntry>
```

Instead of something like https://github.com/globalwordnet/schemas/blob/49b273ecf833cc6acd30074fbdbb771aa9fd8cf8/example.xml#L69-L75

**Comment by goodmami** [comment]
Those aren't examples (i.e., from the gloss lines in WordNet's WNDB data files), but a kind of template string for illustrating syntactic usage. I'm not sure where these (somewhat odd) sentences come from, but in any case the next release will replace them with the standard frames from PWN.
