### ISSUE TITLE
Adjective Markers

### ISSUE THREAD

**Issue by FredsoNerd** [bond-lab/omw-data#8]
In the `PWN:3.0` and `PWN:3.1` data published, I found some Words ending with markers `(a)`, `(p)` and `(ip)`, such as in `complete(a)`, `large(p)` and `regent(ip)`. Those are considered unique Lemmas, but, in fact, there is a property of a Sense describing the markers: the _adjective marks_ are documented in https://wordnet.princeton.edu/documentation/wndb5wn

This is the adjposition property of a sense from https://github.com/globalwordnet/schemas/blob/master/WN-LMF-1.1.dtd#L94

**Comment by goodmami** [comment]
It appears that way, yes. We should collect the list of issues with the OMW's PWN releases so we can fix them for the next release. Maybe these can go in #3?
